myData<-read.csv("C:/Users/baronea/Dropbox/Albany/Intro to Data Analytics/Fish_Stocking_Lists__Actual___Beginning_2011.csv", header=TRUE)
View(myData)
y<-unique(myData$Species)
View(y)
f1<-subset(myData, Species==y[1])
f2<-subset(myData, Species==y[2])
f3<-subset(myData, Species==y[3])
f9<-subset(myData, Species==y[9])
x1<-list(f1$Year)
x2<-list(f2$Year)
x3<-list(f3$Year)
x9<-list(f9$Year)
avgYear1<-aggregate(f1$Size..Inches., by=x1, FUN="mean", na.rm=TRUE)
avgYear2<-aggregate(f2$Size..Inches., by=x2, FUN="mean", na.rm=TRUE)
avgYear3<-aggregate(f3$Size..Inches., by=x3, FUN="mean", na.rm=TRUE)
avgYear9<-aggregate(f9$Size..Inches., by=x9, FUN="mean", na.rm=TRUE)
plot(avgYear1,type="o",xlab="Year",xlim=c(2010,2020),ylim=c(5,11),ylab="Average size in inches",main="Average stocked trout size in NYS")
lines(avgYear2, type="o", col="red")
lines(avgYear3, type="o", col="blue")
lines(avgYear9, type="o", col="orange")
leg=c(y[1],y[2],y[3],y[9])
legColor=c("black","red","blue","orange")
legend(2010.2,5.5,legend=leg, col=legColor, pch=1, horiz=TRUE)